dist: trusty
language: c
os:
  - linux
  - osx
#matrix:
#  allow_failures:
#    - os: osx

addons:
  apt:
    packages:
      - lcov
      - curl
      - xorg-dev
      - libglu1-mesa-dev
  sonarcloud:
    organisation: "godzil-github"
    token: ${SONARCLOUD_TOKEN}

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=OFF -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir sonar; cd sonar; cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=OFF -DCMAKE_BUILD_TYPE=Release ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make clean ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then build-wrapper-linux-x86-64 --out-dir bw-output cmake --build . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd .. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sonar-scanner -Dsonar.login=$SONARCLOUD_TOKEN; fi
  - mkdir coverage
  - cd coverage
  - cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - cmake --build . --target coveralls

cache:
  directories:
    - '$HOME/.sonar/cache'

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew; fi

install: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
