language: c

addons:
  apt:
    packages:
      - lcov
      - curl
      - xorg-dev
      - libglu1-mesa-dev

script:
  - mkdir build
  - cd build
  - cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=OFF -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew; fi

jobs:
  include:
    - os: linux
      dist: bionic
      arch: amd64
      compiler: gcc

    - os: linux
      dist: bionic
      arch: amd64
      compiler: clang

    - os: linux
      dist: focal
      arch: amd64
      compiler: gcc

    - os: linux
      dist: focal
      arch: amd64
      compiler: clang

    - os: osx
      compiler: clang
      osx_image: xcode12.2

    - os: linux
      dist: focal
      arch: arm64
      compiler: gcc

    - os: osx
      compiler: clang
      osx_image: xcode10.3

    - os: osx
      compiler: clang
      osx_image: xcode11.6

    - os: osx
      compiler: clang
      osx_image: xcode12
      
    - stage: "Coverage"
      os: linux
      dist: bionic
      arch: amd64
      compiler: gcc
      script:
        - mkdir coverage
        - cd coverage
        - cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
        - cmake --build .
        - cmake --build . --target coveralls
      after_success:
        - bash <(curl -s https://codecov.io/bash)

  allow_failures:
    - os: linux
      arch: arm64

    - os: osx