language: c
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx

addons:
  apt:
    packages:
      - lcov
      - curl
      - xorg-dev
      - libglu1-mesa-dev

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=OFF -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - cd ..
  - mkdir coverage
  - cd coverage
  - cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - cmake --build . --target coveralls

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew; fi

install: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
