language: c
git:
 submodule: true
compiler:
 - clang
 - gcc
script: 
 - mkdir build
 - cd build 
 - cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=OFF -DCMAKE_BUILD_TYPE=Release .. 
 - cmake --build . 
 - cd ..
 - mkdir coverage 
 - cd coverage
 - cmake -DUSE_ALLEGRO=OFF -DUSE_PROFILING=OFF -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
 - cmake --build .
 - cmake --build . --target coveralls
install: true
env:
  global:
    - CODECOV_TOKEN=$COVERALLS_REPO_TOKEN
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - lcov
      - curl
after_success:
  - bash <(curl -s https://codecov.io/bash)
